site_name: reponsive-data
repo_url: https://github.com/thomas-lehmann-private/responsive-data
site_author: Thomas Lehmann
site_description: Library for making data responsive

nav:
  - index.md
  - design.md
  - responsive-data-handling.md
  - subject-observer.md
  - the-build-process.md
  - how-to-write-performance-tests.md

theme:
  name: "material"

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs/examples
  - pymdownx.superfences
  - toc:
      permalink: True

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
  - autolinks
